[package]
name = "py_cpp_demangle"
version = "0.1.0"
authors = ["Ben Frederickson <github@benfrederickson.com>"]
edition = "2018"

[lib]
name = "py_cpp_demangle"
crate-type = ["cdylib"]

[dependencies]
cpp_demangle = "0.2.12"

[dependencies.pyo3]
version = "0.7"
features = ["extension-module"]
